[package]
name = "astropress"
version = "0.1.0"
edition = "2018"
authors = ["khyperia <khyperia@live.com>"]

[dependencies]
failure = "*"
lazy_static = "*"
nalgebra = "*"
png = "*"
rayon = "*"

[dev-dependencies]
rand = "*"